DROP TABLE IF EXISTS "BudgetPlan";
DROP TABLE IF EXISTS "TransactionHistory";
DROP TABLE IF EXISTS "Goal";
DROP TABLE IF EXISTS "Expense";
DROP TABLE IF EXISTS "Accounts";
DROP TABLE IF EXISTS "Roles";