// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: block_bruteforce.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBlockBruteForce = `-- name: CreateBlockBruteForce :one
INSERT INTO "BlockBruteForce" (
  "Email", "Count", "Status", 
  "LockedTime", "UnLockTime", "CreatedAt", "CreatedBy"
) 
VALUES (
  $1, $2, $3, 
  $4, $5, $6, $7
)
RETURNING "Id", "Email", "Count", "Status", "LockedTime", "UnLockTime", "CreatedAt", "UpdatedAt", "CreatedBy", "UpdatedBy"
`

type CreateBlockBruteForceParams struct {
	Email      string             `json:"Email"`
	Count      pgtype.Int4        `json:"Count"`
	Status     string             `json:"Status"`
	LockedTime pgtype.Timestamptz `json:"LockedTime"`
	UnLockTime pgtype.Timestamptz `json:"UnLockTime"`
	CreatedAt  pgtype.Timestamptz `json:"CreatedAt"`
	CreatedBy  pgtype.Text        `json:"CreatedBy"`
}

func (q *Queries) CreateBlockBruteForce(ctx context.Context, arg CreateBlockBruteForceParams) (BlockBruteForce, error) {
	row := q.db.QueryRow(ctx, createBlockBruteForce,
		arg.Email,
		arg.Count,
		arg.Status,
		arg.LockedTime,
		arg.UnLockTime,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var i BlockBruteForce
	err := row.Scan(
		&i.Id,
		&i.Email,
		&i.Count,
		&i.Status,
		&i.LockedTime,
		&i.UnLockTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteBlockBruteForce = `-- name: DeleteBlockBruteForce :one
DELETE FROM "BlockBruteForce"
WHERE "Id" = $1
RETURNING "Id", "Email", "Count", "Status", "LockedTime", "UnLockTime", "CreatedAt", "UpdatedAt", "CreatedBy", "UpdatedBy"
`

func (q *Queries) DeleteBlockBruteForce(ctx context.Context, id uuid.UUID) (BlockBruteForce, error) {
	row := q.db.QueryRow(ctx, deleteBlockBruteForce, id)
	var i BlockBruteForce
	err := row.Scan(
		&i.Id,
		&i.Email,
		&i.Count,
		&i.Status,
		&i.LockedTime,
		&i.UnLockTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getBlockBruteForceByEmail = `-- name: GetBlockBruteForceByEmail :one
SELECT "Id", "Email", "Count", "Status", "LockedTime", "UnLockTime", "CreatedAt", "UpdatedAt", "CreatedBy", "UpdatedBy" 
FROM "BlockBruteForce" 
WHERE "Email" = $1 LIMIT 1
`

func (q *Queries) GetBlockBruteForceByEmail(ctx context.Context, email string) (BlockBruteForce, error) {
	row := q.db.QueryRow(ctx, getBlockBruteForceByEmail, email)
	var i BlockBruteForce
	err := row.Scan(
		&i.Id,
		&i.Email,
		&i.Count,
		&i.Status,
		&i.LockedTime,
		&i.UnLockTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getBlockBruteForceById = `-- name: GetBlockBruteForceById :one
SELECT "Id", "Email", "Count", "Status", "LockedTime", "UnLockTime", "CreatedAt", "UpdatedAt", "CreatedBy", "UpdatedBy" 
FROM "BlockBruteForce" 
WHERE "Id" = $1 LIMIT 1
`

func (q *Queries) GetBlockBruteForceById(ctx context.Context, id uuid.UUID) (BlockBruteForce, error) {
	row := q.db.QueryRow(ctx, getBlockBruteForceById, id)
	var i BlockBruteForce
	err := row.Scan(
		&i.Id,
		&i.Email,
		&i.Count,
		&i.Status,
		&i.LockedTime,
		&i.UnLockTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateBlockBruteForce = `-- name: UpdateBlockBruteForce :one
UPDATE "BlockBruteForce"
SET 
  "Email" = COALESCE($1, "Email"),
  "Count" = COALESCE($2, "Count"),
  "Status" = COALESCE($3, "Status"),
  "LockedTime" = $4,
  "UnLockTime" = $5,
  "UpdatedAt" = COALESCE($6, "UpdatedAt"),
  "UpdatedBy" = COALESCE($7, "UpdatedBy")
WHERE "Id" = $8
RETURNING "Id", "Email", "Count", "Status", "LockedTime", "UnLockTime", "CreatedAt", "UpdatedAt", "CreatedBy", "UpdatedBy"
`

type UpdateBlockBruteForceParams struct {
	Email      pgtype.Text        `json:"email"`
	Count      pgtype.Int4        `json:"count"`
	Status     pgtype.Text        `json:"status"`
	Lockedtime pgtype.Timestamptz `json:"lockedtime"`
	Unlocktime pgtype.Timestamptz `json:"unlocktime"`
	Updatedat  pgtype.Timestamptz `json:"updatedat"`
	Updatedby  pgtype.Text        `json:"updatedby"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateBlockBruteForce(ctx context.Context, arg UpdateBlockBruteForceParams) (BlockBruteForce, error) {
	row := q.db.QueryRow(ctx, updateBlockBruteForce,
		arg.Email,
		arg.Count,
		arg.Status,
		arg.Lockedtime,
		arg.Unlocktime,
		arg.Updatedat,
		arg.Updatedby,
		arg.ID,
	)
	var i BlockBruteForce
	err := row.Scan(
		&i.Id,
		&i.Email,
		&i.Count,
		&i.Status,
		&i.LockedTime,
		&i.UnLockTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
