// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: lkplanwise_session.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLKPlanWiseSession = `-- name: CreateLKPlanWiseSession :one
INSERT INTO "LKPlanWiseSession" (
  "AccountId", "LoginAt", "Platform", "Os", "Browser", 
  "LoginIp", "IssuedTime", "ExpirationTime", "SessionStatus", 
  "Token", "RefreshTokenAt", "CreatedAt", "CreatedBy"
) 
VALUES (
  $1, $2, $3, $4, $5, 
  $6, $7, $8, $9, 
  $10, $11, $12, $13
) 
RETURNING "Id", "AccountId", "LoginAt", "Platform", "Os", "Browser", "LoginIp", "IssuedTime", "ExpirationTime", "SessionStatus", "Token", "RefreshTokenAt", "CreatedAt", "UpdatedAt", "CreatedBy", "UpdatedBy"
`

type CreateLKPlanWiseSessionParams struct {
	AccountId      pgtype.UUID        `json:"AccountId"`
	LoginAt        pgtype.Timestamptz `json:"LoginAt"`
	Platform       pgtype.Text        `json:"Platform"`
	Os             pgtype.Text        `json:"Os"`
	Browser        pgtype.Text        `json:"Browser"`
	LoginIp        string             `json:"LoginIp"`
	IssuedTime     pgtype.Timestamptz `json:"IssuedTime"`
	ExpirationTime pgtype.Timestamptz `json:"ExpirationTime"`
	SessionStatus  string             `json:"SessionStatus"`
	Token          pgtype.Text        `json:"Token"`
	RefreshTokenAt pgtype.Timestamptz `json:"RefreshTokenAt"`
	CreatedAt      pgtype.Timestamptz `json:"CreatedAt"`
	CreatedBy      pgtype.Text        `json:"CreatedBy"`
}

func (q *Queries) CreateLKPlanWiseSession(ctx context.Context, arg CreateLKPlanWiseSessionParams) (LKPlanWiseSession, error) {
	row := q.db.QueryRow(ctx, createLKPlanWiseSession,
		arg.AccountId,
		arg.LoginAt,
		arg.Platform,
		arg.Os,
		arg.Browser,
		arg.LoginIp,
		arg.IssuedTime,
		arg.ExpirationTime,
		arg.SessionStatus,
		arg.Token,
		arg.RefreshTokenAt,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var i LKPlanWiseSession
	err := row.Scan(
		&i.Id,
		&i.AccountId,
		&i.LoginAt,
		&i.Platform,
		&i.Os,
		&i.Browser,
		&i.LoginIp,
		&i.IssuedTime,
		&i.ExpirationTime,
		&i.SessionStatus,
		&i.Token,
		&i.RefreshTokenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteLKPlanWiseSession = `-- name: DeleteLKPlanWiseSession :one
DELETE FROM "LKPlanWiseSession"
WHERE "Id" = $1
RETURNING "Id", "AccountId", "LoginAt", "Platform", "Os", "Browser", "LoginIp", "IssuedTime", "ExpirationTime", "SessionStatus", "Token", "RefreshTokenAt", "CreatedAt", "UpdatedAt", "CreatedBy", "UpdatedBy"
`

func (q *Queries) DeleteLKPlanWiseSession(ctx context.Context, id uuid.UUID) (LKPlanWiseSession, error) {
	row := q.db.QueryRow(ctx, deleteLKPlanWiseSession, id)
	var i LKPlanWiseSession
	err := row.Scan(
		&i.Id,
		&i.AccountId,
		&i.LoginAt,
		&i.Platform,
		&i.Os,
		&i.Browser,
		&i.LoginIp,
		&i.IssuedTime,
		&i.ExpirationTime,
		&i.SessionStatus,
		&i.Token,
		&i.RefreshTokenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getLKPlanWiseSessionById = `-- name: GetLKPlanWiseSessionById :one
SELECT "Id", "AccountId", "LoginAt", "Platform", "Os", "Browser", "LoginIp", "IssuedTime", "ExpirationTime", "SessionStatus", "Token", "RefreshTokenAt", "CreatedAt", "UpdatedAt", "CreatedBy", "UpdatedBy" 
FROM "LKPlanWiseSession" 
WHERE "Id" = $1
`

func (q *Queries) GetLKPlanWiseSessionById(ctx context.Context, id uuid.UUID) (LKPlanWiseSession, error) {
	row := q.db.QueryRow(ctx, getLKPlanWiseSessionById, id)
	var i LKPlanWiseSession
	err := row.Scan(
		&i.Id,
		&i.AccountId,
		&i.LoginAt,
		&i.Platform,
		&i.Os,
		&i.Browser,
		&i.LoginIp,
		&i.IssuedTime,
		&i.ExpirationTime,
		&i.SessionStatus,
		&i.Token,
		&i.RefreshTokenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getLKPlanWiseSessionForLogin = `-- name: GetLKPlanWiseSessionForLogin :one
SELECT "Id", "AccountId", "LoginAt", "Platform", "Os", "Browser", "LoginIp", "IssuedTime", "ExpirationTime", "SessionStatus", "Token", "RefreshTokenAt", "CreatedAt", "UpdatedAt", "CreatedBy", "UpdatedBy" 
FROM "LKPlanWiseSession" 
WHERE "AccountId" = $1 AND "LoginIp" = $2
`

type GetLKPlanWiseSessionForLoginParams struct {
	AccountId pgtype.UUID `json:"AccountId"`
	LoginIp   string      `json:"LoginIp"`
}

func (q *Queries) GetLKPlanWiseSessionForLogin(ctx context.Context, arg GetLKPlanWiseSessionForLoginParams) (LKPlanWiseSession, error) {
	row := q.db.QueryRow(ctx, getLKPlanWiseSessionForLogin, arg.AccountId, arg.LoginIp)
	var i LKPlanWiseSession
	err := row.Scan(
		&i.Id,
		&i.AccountId,
		&i.LoginAt,
		&i.Platform,
		&i.Os,
		&i.Browser,
		&i.LoginIp,
		&i.IssuedTime,
		&i.ExpirationTime,
		&i.SessionStatus,
		&i.Token,
		&i.RefreshTokenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateLKPlanWiseSession = `-- name: UpdateLKPlanWiseSession :one
UPDATE "LKPlanWiseSession"
SET 
  "AccountId" = COALESCE($2, "AccountId"),
  "LoginAt" = COALESCE($3, "LoginAt"),
  "Platform" = COALESCE($4, "Platform"),
  "Os" = COALESCE($5, "Os"),
  "Browser" = COALESCE($6, "Browser"),
  "LoginIp" = COALESCE($7, "LoginIp"),
  "IssuedTime" = COALESCE($8, "IssuedTime"),
  "ExpirationTime" = COALESCE($9, "ExpirationTime"),
  "SessionStatus" = COALESCE($10, "SessionStatus"),
  "Token" = COALESCE($11, "Token"),
  "RefreshTokenAt" = COALESCE($12, "RefreshTokenAt"),
  "UpdatedAt" = COALESCE($13, "UpdatedAt"),
  "UpdatedBy" = COALESCE($14, "UpdatedBy")
WHERE "Id" = $1
RETURNING "Id", "AccountId", "LoginAt", "Platform", "Os", "Browser", "LoginIp", "IssuedTime", "ExpirationTime", "SessionStatus", "Token", "RefreshTokenAt", "CreatedAt", "UpdatedAt", "CreatedBy", "UpdatedBy"
`

type UpdateLKPlanWiseSessionParams struct {
	Id             uuid.UUID          `json:"Id"`
	AccountId      pgtype.UUID        `json:"AccountId"`
	LoginAt        pgtype.Timestamptz `json:"LoginAt"`
	Platform       pgtype.Text        `json:"Platform"`
	Os             pgtype.Text        `json:"Os"`
	Browser        pgtype.Text        `json:"Browser"`
	LoginIp        string             `json:"LoginIp"`
	IssuedTime     pgtype.Timestamptz `json:"IssuedTime"`
	ExpirationTime pgtype.Timestamptz `json:"ExpirationTime"`
	SessionStatus  string             `json:"SessionStatus"`
	Token          pgtype.Text        `json:"Token"`
	RefreshTokenAt pgtype.Timestamptz `json:"RefreshTokenAt"`
	UpdatedAt      pgtype.Timestamptz `json:"UpdatedAt"`
	UpdatedBy      pgtype.Text        `json:"UpdatedBy"`
}

func (q *Queries) UpdateLKPlanWiseSession(ctx context.Context, arg UpdateLKPlanWiseSessionParams) (LKPlanWiseSession, error) {
	row := q.db.QueryRow(ctx, updateLKPlanWiseSession,
		arg.Id,
		arg.AccountId,
		arg.LoginAt,
		arg.Platform,
		arg.Os,
		arg.Browser,
		arg.LoginIp,
		arg.IssuedTime,
		arg.ExpirationTime,
		arg.SessionStatus,
		arg.Token,
		arg.RefreshTokenAt,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	var i LKPlanWiseSession
	err := row.Scan(
		&i.Id,
		&i.AccountId,
		&i.LoginAt,
		&i.Platform,
		&i.Os,
		&i.Browser,
		&i.LoginIp,
		&i.IssuedTime,
		&i.ExpirationTime,
		&i.SessionStatus,
		&i.Token,
		&i.RefreshTokenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
