// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Account struct {
	ID           uuid.UUID      `json:"id"`
	Username     string         `json:"username"`
	Firstname    sql.NullString `json:"firstname"`
	Lastname     sql.NullString `json:"lastname"`
	Email        sql.NullString `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	DateOfBirth  sql.NullTime   `json:"date_of_birth"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	CreatedBy    sql.NullString `json:"created_by"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	UpdatedBy    sql.NullString `json:"updated_by"`
}

type AccountRole struct {
	AccountID uuid.UUID      `json:"account_id"`
	RoleID    uuid.UUID      `json:"role_id"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	CreatedBy sql.NullString `json:"created_by"`
	UpdatedBy sql.NullString `json:"updated_by"`
}

type Role struct {
	ID        uuid.UUID      `json:"id"`
	RoleCode  string         `json:"role_code"`
	RoleName  sql.NullString `json:"role_name"`
	CreatedAt sql.NullTime   `json:"created_at"`
	CreatedBy sql.NullString `json:"created_by"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	UpdatedBy sql.NullString `json:"updated_by"`
}
