// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	Id             uuid.UUID          `json:"Id"`
	UserName       string             `json:"UserName"`
	FirstName      pgtype.Text        `json:"FirstName"`
	LastName       pgtype.Text        `json:"LastName"`
	Email          string             `json:"Email"`
	PasswordHash   pgtype.Text        `json:"PasswordHash"`
	DateOfBirth    pgtype.Text        `json:"DateOfBirth"`
	RoleId         uuid.UUID          `json:"RoleId"`
	IsMailVerified bool               `json:"IsMailVerified"`
	IsLocked       bool               `json:"IsLocked"`
	CreatedAt      pgtype.Timestamptz `json:"CreatedAt"`
	UpdatedAt      pgtype.Timestamptz `json:"UpdatedAt"`
	CreatedBy      pgtype.Text        `json:"CreatedBy"`
	UpdatedBy      pgtype.Text        `json:"UpdatedBy"`
}

type BlockBruteForce struct {
	Id         uuid.UUID          `json:"Id"`
	Email      string             `json:"Email"`
	Count      pgtype.Int4        `json:"Count"`
	Status     string             `json:"Status"`
	LockedTime pgtype.Timestamptz `json:"LockedTime"`
	UnLockTime pgtype.Timestamptz `json:"UnLockTime"`
	CreatedAt  pgtype.Timestamptz `json:"CreatedAt"`
	UpdatedAt  pgtype.Timestamptz `json:"UpdatedAt"`
	CreatedBy  pgtype.Text        `json:"CreatedBy"`
	UpdatedBy  pgtype.Text        `json:"UpdatedBy"`
}

type BudgetPlan struct {
	Id            uuid.UUID          `json:"Id"`
	AccountId     uuid.UUID          `json:"AccountId"`
	Month         pgtype.Text        `json:"Month"`
	TotalIncome   pgtype.Numeric     `json:"TotalIncome"`
	TotalExpenses pgtype.Numeric     `json:"TotalExpenses"`
	SavingsGoal   pgtype.Numeric     `json:"SavingsGoal"`
	CreatedAt     pgtype.Timestamptz `json:"CreatedAt"`
	UpdatedAt     pgtype.Timestamptz `json:"UpdatedAt"`
	CreatedBy     pgtype.Text        `json:"CreatedBy"`
	UpdatedBy     pgtype.Text        `json:"UpdatedBy"`
}

type Expense struct {
	Id          uuid.UUID          `json:"Id"`
	AccountId   uuid.UUID          `json:"AccountId"`
	Category    pgtype.Text        `json:"Category"`
	Amount      pgtype.Numeric     `json:"Amount"`
	Date        pgtype.Timestamptz `json:"Date"`
	Description pgtype.Text        `json:"Description"`
	CreatedAt   pgtype.Timestamptz `json:"CreatedAt"`
	UpdatedAt   pgtype.Timestamptz `json:"UpdatedAt"`
	CreatedBy   pgtype.Text        `json:"CreatedBy"`
	UpdatedBy   pgtype.Text        `json:"UpdatedBy"`
}

type Goal struct {
	Id            uuid.UUID          `json:"Id"`
	AccountId     uuid.UUID          `json:"AccountId"`
	GoalType      pgtype.Text        `json:"GoalType"`
	TargetAmount  pgtype.Numeric     `json:"TargetAmount"`
	CurrentAmount pgtype.Numeric     `json:"CurrentAmount"`
	Deadline      pgtype.Timestamptz `json:"Deadline"`
	Progress      pgtype.Numeric     `json:"Progress"`
	CreatedAt     pgtype.Timestamptz `json:"CreatedAt"`
	UpdatedAt     pgtype.Timestamptz `json:"UpdatedAt"`
	CreatedBy     pgtype.Text        `json:"CreatedBy"`
	UpdatedBy     pgtype.Text        `json:"UpdatedBy"`
}

type LKPlanWiseSession struct {
	Id             uuid.UUID          `json:"Id"`
	AccountId      pgtype.UUID        `json:"AccountId"`
	LoginAt        pgtype.Timestamptz `json:"LoginAt"`
	Platform       pgtype.Text        `json:"Platform"`
	Os             pgtype.Text        `json:"Os"`
	Browser        pgtype.Text        `json:"Browser"`
	LoginIp        string             `json:"LoginIp"`
	IssuedTime     pgtype.Timestamptz `json:"IssuedTime"`
	ExpirationTime pgtype.Timestamptz `json:"ExpirationTime"`
	SessionStatus  string             `json:"SessionStatus"`
	RefreshToken   pgtype.Text        `json:"RefreshToken"`
	RefreshTokenAt pgtype.Timestamptz `json:"RefreshTokenAt"`
	CreatedAt      pgtype.Timestamptz `json:"CreatedAt"`
	UpdatedAt      pgtype.Timestamptz `json:"UpdatedAt"`
	CreatedBy      pgtype.Text        `json:"CreatedBy"`
	UpdatedBy      pgtype.Text        `json:"UpdatedBy"`
}

type Role struct {
	Id        uuid.UUID          `json:"Id"`
	RoleCode  string             `json:"RoleCode"`
	RoleName  pgtype.Text        `json:"RoleName"`
	CreatedAt pgtype.Timestamptz `json:"CreatedAt"`
	UpdatedAt pgtype.Timestamptz `json:"UpdatedAt"`
	CreatedBy pgtype.Text        `json:"CreatedBy"`
	UpdatedBy pgtype.Text        `json:"UpdatedBy"`
}

type TransactionHistory struct {
	Id              uuid.UUID          `json:"Id"`
	AccountId       uuid.UUID          `json:"AccountId"`
	TransactionType pgtype.Text        `json:"TransactionType"`
	Amount          pgtype.Numeric     `json:"Amount"`
	Description     pgtype.Text        `json:"Description"`
	CreatedAt       pgtype.Timestamptz `json:"CreatedAt"`
	UpdatedAt       pgtype.Timestamptz `json:"UpdatedAt"`
	CreatedBy       pgtype.Text        `json:"CreatedBy"`
	UpdatedBy       pgtype.Text        `json:"UpdatedBy"`
}

type VerifyEmail struct {
	Id         int64     `json:"Id"`
	UserName   string    `json:"UserName"`
	Email      string    `json:"Email"`
	SecretCode string    `json:"SecretCode"`
	IsUsed     bool      `json:"IsUsed"`
	CreatedAt  time.Time `json:"CreatedAt"`
	ExpiredAt  time.Time `json:"ExpiredAt"`
}
