// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	DeleteAccountByID(ctx context.Context, id uuid.UUID) error
	DeleteRole(ctx context.Context, id uuid.UUID) error
	GetAccountByID(ctx context.Context, id uuid.UUID) (GetAccountByIDRow, error)
	GetAccountByUsername(ctx context.Context, username string) (GetAccountByUsernameRow, error)
	GetAccountRolesByAccountId(ctx context.Context, accountID uuid.UUID) ([]AccountRole, error)
	GetAccountRolesByRoleId(ctx context.Context, roleID uuid.UUID) ([]AccountRole, error)
	GetAccountsByRole(ctx context.Context, roleID uuid.UUID) ([]Account, error)
	GetAllAccountRoles(ctx context.Context) ([]AccountRole, error)
	GetRole(ctx context.Context, id uuid.UUID) (Role, error)
	GetRoleByCode(ctx context.Context, roleCode string) (Role, error)
	InsertAccount(ctx context.Context, arg InsertAccountParams) error
	InsertAccountRole(ctx context.Context, arg InsertAccountRoleParams) error
	ListAllAccounts(ctx context.Context, arg ListAllAccountsParams) ([]ListAllAccountsRow, error)
	ListRoles(ctx context.Context, arg ListRolesParams) ([]Role, error)
	RemoveRoleFromAccount(ctx context.Context, arg RemoveRoleFromAccountParams) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) error
	UpdateAccountsRoles(ctx context.Context, arg UpdateAccountsRolesParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
}

var _ Querier = (*Queries)(nil)
